# Generated by Django 2.1 on 2021-11-10 11:39

import cloth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to=cloth.models.photo_path)),
                ('content', models.CharField(blank=True, help_text='최대 140자 입력 가능', max_length=140)),
                ('season', models.CharField(choices=[('사계절', '사계절'), ('봄', '봄'), ('여름', '여름'), ('가을', '가을'), ('겨울', '겨울')], default='N', max_length=10, verbose_name='계절(선택사항)')),
                ('part', models.CharField(choices=[('상의', '상의'), ('하의', '하의')], default='N', max_length=10, verbose_name='부위(선택사항)')),
                ('r_color', models.IntegerField(default=0)),
                ('g_color', models.IntegerField(default=0)),
                ('b_color', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
