# Generated by Django 2.1 on 2021-11-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='content',
        ),
    ]
