# Generated by Django 2.1 on 2021-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_remove_cloth_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='b_color',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='g_color',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='r_color',
            field=models.IntegerField(default=10),
        ),
    ]
