# Generated by Django 3.2.9 on 2021-12-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cpation',
            new_name='caption',
        ),
    ]
